[build]
  publish = "."
  command = ""

  functions = "netlify/functions"

[functions]
  included_files = ["draftkings-odds.js", "espn-injury-check-results.js"]

[[redirects]]
  from = "/api/:scan"
  to = "/.netlify/functions/:scan"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
